language: node_js
node_js: "8"
cache: npm

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install && npm link
  - cd creator && npm install && ./node_module/.bin/electron-rebuild

script:
  - cocos-creator --path templates/hello-world --build="platform=web-mobile"
